name: Build & publish static site

##############################################################################
# 1.  Any push to main fires the job
##############################################################################
on:
  push:
    branches: [ main ]

##############################################################################
# 2.  Allow the job to push commits back into the repo
##############################################################################
permissions:
  contents: write        # <- this removes the 403

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ── 2.1  Checkout source
      - uses: actions/checkout@v4

      # ── 2.2  Build (adjust to pnpm/yarn if you prefer)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build              # ⇒ dist/

      # ── 2.3  Switch to branch `deploy`, using dist/ as work-tree
      - name: Publish dist/ to deploy branch
        run: |
          # set an identity for the CI commit
          git config --global user.email "ci@vitlikisstovan.fo"
          git config --global user.name  "Vitliki CI Bot"

          # create / update branch but keep history clean
          git --work-tree=dist checkout -B deploy

          # optional SPA fallback + nojekyll
          printf "RewriteEngine On\nRewriteCond %%{REQUEST_FILENAME} !-f\nRewriteCond %%{REQUEST_FILENAME} !-d\nRewriteRule ^ /index.html [L]\n" > dist/.htaccess
          touch dist/.nojekyll

          # commit ONLY what's inside dist/
          git --work-tree=dist add -A
          git --work-tree=dist commit -m "deploy $GITHUB_SHA" || echo "nothing to commit"

          # force-push deploy branch
          git push -f origin deploy
