name: Build & publish static site

on:
  push:
    branches: [ main ]               # ← your source branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1 — check out the source
      - uses: actions/checkout@v4

      # 2 — build (adjust if you use pnpm / yarn)
      - uses: actions/setup-node@v4
        with: {node-version: 20, cache: npm}
      - run: npm ci
      - run: npm run build            # ➜ dist/

      # 3 — publish dist/ to branch `deploy`
      - name: Push to deploy branch
        run: |
          # tell Git to treat dist/ as the working tree
          git --work-tree=dist checkout -B deploy
          
          # optional SPA fallback + GH convenience files
          echo -e "RewriteEngine On\nRewriteCond %{REQUEST_FILENAME} !-f\nRewriteCond %{REQUEST_FILENAME} !-d\nRewriteRule ^ /index.html [L]" > dist/.htaccess
          touch dist/.nojekyll
          
          # commit & force-push
          git --work-tree=dist add -A
          git --work-tree=dist commit -m "deploy $GITHUB_SHA" || true
          git push -f origin deploy
